### ISSUE TITLE
Customise 2d planar sheet generation

### ISSUE THREAD

**Issue by jonathan-f** [DamCB/tyssue-demo#3]
Dear @sophietheis , thanks for developing this amazing package! I was following the rosettes.ipynb notebook to generate 2d planar sheets and collapse edges.
Shortly, I would like to generate sheets in the positive (x-y) plane, with cells typically 10 microns long, and including noise, but I have some questions:
1) Is there a way to set a seed in order to get the same initial configuration when re-running?
2) Is it possible to get the configurations in the positive (x-y) plane? 
3) Re-running the same code with the same parameters result in configurations with very different average cell area and different number of cells; I understand that the presence of noise will result in different configurations, but is there a way to stabilise the average cell area?

Here is my code and two examples of the outcome:
`sheet = Sheet.planar_sheet_2d('flat', 5, 5, 10, 10, noise=0.2)`
`sheet.sanitize(trim_borders=True)`
`geom.update_all(sheet)`
`sheet.update_rank()`
`model = model_factory(
    [
        effectors.LineTension,
        effectors.FaceContractility,
        effectors.FaceAreaElasticity
    ]
)`

`specs = {
    "face": {
        "contractility": 5e-2,
        "prefered_area": sheet.face_df.area.mean(),
        "area_elasticity": 1.
    },
    "edge": {
        "line_tension": 1e-2,
        "is_active": 1
    },
    "vert": {
        "is_active": 1
    },
}`

`sheet.update_specs(specs, reset=True)`
`solver = QSSolver()`
`res = solver.find_energy_min(sheet, geom, model)`
`fig, ax = sheet_view(sheet, mode="quick")`
`plt.scatter(sheet.face_df['x'],sheet.face_df['y'])`

<img width="329" alt="Screenshot 2020-11-10 at 19 08 07" src="https://user-images.githubusercontent.com/54023927/98713586-17fe5380-2388-11eb-81c7-448d90d1a236.png">
<img width="329" alt="Screenshot 2020-11-10 at 19 04 59" src="https://user-images.githubusercontent.com/54023927/98713594-1a60ad80-2388-11eb-97a3-a7420a27f518.png">

Thank you in advance!
Best,
Jonathan

**Comment by sophietheis** [comment]
Hi @jonathan-f,

We are glad that you appreciate the package!

To answer yours questions : 
	1- If you find a tissue that look find to you, you can save it and reopen for reuse. 
Save with:
```python
from tyssue.io import hdf5
hdf5.save_datasets('your_tissue.hf5', sheet)
```
Load with:
```python
dsets = hdf5.load_datasets('your_tissue.hf5',
                            data_names=['vert', 'edge', 'face'])
sheet = Sheet('tissue', dsets)
```
2- There is no configuration to force the tissue to be in the positive plane. The simplest solution is to transpose if there is negative coordinate. 
```python
min_x = sheet.vert_df['x'].min()
min_y = sheet.vert_df['y'].min()
if min_x<0:
	sheet.vert_df['x'] += abs(min_x)
if min_y<0:
	sheet.vert_df['y'] += abs(min_y)
```
3- You have to scale the cell area to avoid to much difference un average cell area. 
	To stabilise the same number of cell, since your patch is small, you can automatically rerun the creation patch code until you reach the number of cell that you want. 
```python
wanted_number_cell = 7

sheet = Sheet.planar_sheet_2d('flat', 5, 5, 10, 10, noise=0.2)
sheet.sanitize(trim_borders=True)
geom.update_all(sheet)
sheet.update_rank()

while sheet.Nf != wanted_number_cell :
	sheet = Sheet.planar_sheet_2d('flat', 5, 5, 10, 10, noise=0.2)
	sheet.sanitize(trim_borders=True)
	geom.update_all(sheet)
	sheet.update_rank()

```

I hope it helps.
Regards,
Sophie

**Comment by jonathan-f** [comment]
Hi @sophietheis, thank you very much for your reply, it is very helpful!

Best wishes,
Jonathan
